### Question 1:

In [5]:
import numpy as np

array1 = np.full((2,3),6)
print(array1)
list_from_array = array1.tolist()
print(list_from_array)

[[6 6 6]
 [6 6 6]]
[[6, 6, 6], [6, 6, 6]]


### Question 2:

In [10]:
import numpy as np

array1 = np.array([[5,8,8],[3,7,4],[8,9,1]])
print(array1)
list_from_array = array1.trace()
print(list_from_array)

[[5 8 8]
 [3 7 4]
 [8 9 1]]
13


In [10]:
import numpy as np

array1 = np.array([[5,8,8],[3,7,4],[8,9,1]])
print(array1)
sum=0
for i in range(0,array1.shape[0]):
    sum = sum + array1[i,i]
print(sum)

[[5 8 8]
 [3 7 4]
 [8 9 1]]
13


### Question3:

In [19]:
import numpy as np

list1=[]
x=3
array1 = np.array([[5,8,8],[3,7,4],[8,9,1]])
print (array1.shape)
for i in range(0,array1.shape[0]):
    for l in range(0,array1.shape[1]):
        if array1[i,l]>=x:
            list1.append(array1[i,l])
print(f"Numbers greater than x are: {list1}")


(3, 3)
Numbers greater than x are: [5, 8, 8, 3, 7, 4, 8, 9]


### Question 4:

In [21]:
import numpy as np

array1 = np.array([[5,8,8],[3,7,4],[8,9,1]])
array2 = np.array([[9,3,5],[5,3,4],[3,7,11]])

array3=array1+array2
print(f"our new array is: \n \n {array3}")

our new array is: 
 
 [[14 11 13]
 [ 8 10  8]
 [11 16 12]]


### Question 5:

In [25]:
import numpy as np

array1 = np.array([[5,8,8],[3,7,2],[8,9,1]])
print(f"our array is: \n  {array1}")
print(f"The mean of each row of our array is: {np.mean(array1, axis = 1)}")

our array is: 
  [[5 8 8]
 [3 7 2]
 [8 9 1]]
The mean of each row of our array is: [7. 4. 6.]
